name: Build
on: [push]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: full

jobs:
  build-windows:
    runs-on: windows-latest
    env:
      RUSTFLAGS: "-C target-feature=+crt-static"
      TARGET: x86_64-pc-windows-msvc
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ env.TARGET }}

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-

      - run: cargo fmt --check
      - run: cargo update
      - run: cargo clippy -- -D warnings
      - run: cargo build --release --target ${{ env.TARGET }}

      - name: Compress Binary
        run: |
          $FILE = "osu-bdi-$($env:GITHUB_SHA.Substring(0, 7))-$($env:TARGET).xz"
          echo "FILE=$FILE" >> $env:GITHUB_ENV
          7z a $FILE target/${{ env.TARGET }}/release/osu-bdi.exe

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.FILE }}
          path: ${{ env.FILE }}
